### ISSUE TITLE
[Illegal Items] NoSuchMethod error when opening ender chests

### ISSUE THREAD

**Issue by LysergikProductions** [LysergikProductions/RVAS-Core#69]
**Describe the bug**
```
30.05 02:53:32 [Server] ERROR Could not pass event InventoryOpenEvent to core v0.3
30.05 02:53:32 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.displayName()Lnet/kyori/adventure/text/Component;
30.05 02:53:32 [Server] INFO at core.backend.ItemCheck.IllegalCheck(ItemCheck.java:138) ~[?:?]
30.05 02:53:32 [Server] INFO at core.backend.ItemCheck.lambda$IllegalCheck$0(ItemCheck.java:77) ~[?:?]
30.05 02:53:32 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_201]
30.05 02:53:32 [Server] INFO at core.backend.ItemCheck.IllegalCheck(ItemCheck.java:71) ~[?:?]
30.05 02:53:32 [Server] INFO at core.events.ItemCheckTriggers.lambda$onOpenInventory$0(ItemCheckTriggers.java:29) ~[?:?]
```

**Steps To Reproduce**
1. Enter the game
2. Open an ender chest

**Reproducibility**
Always

**Expected behavior**
The event is dealt with appropriately

**Minecraft Client Version**
1.16.4

**Comment by LysergikProductions** [comment]
Fixed in next commit. Closing as fixed.
